#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from sqlalchemy import DATE, NVARCHAR, FLOAT, BIGINT, SmallInteger, DATETIME
from sqlalchemy.dialects.mysql import BIT
import talib as tl
from instock.core.strategy import enter
from instock.core.strategy import turtle_trade
from instock.core.strategy import climax_limitdown
from instock.core.strategy import low_atr
from instock.core.strategy import backtrace_ma250
from instock.core.strategy import breakthrough_platform
from instock.core.strategy import parking_apron
from instock.core.strategy import low_backtrace_increase
from instock.core.strategy import keep_increasing
from instock.core.strategy import high_tight_flag

__author__ = 'myh '
__date__ = '2023/3/10 '

RATE_FIELDS_COUNT = 100  # Number of fields for N-day rate of return, i.e., N value

TABLE_CN_STOCK_ATTENTION = {'name': 'cn_stock_attention', 'en': 'My Watchlist',
                            'columns': {'datetime': {'type': DATETIME, 'en': 'Date', 'size': 0},
                                        'code': {'type': NVARCHAR(6), 'en': 'Code', 'size': 60}}}

TABLE_CN_ETF_SPOT = {'name': 'cn_etf_spot', 'en': 'Daily ETF Data',
                     'columns': {'date': {'type': DATE, 'en': 'Date', 'size': 0},
                                 'code': {'type': NVARCHAR(6), 'en': 'Code', 'size': 60},
                                 'name': {'type': NVARCHAR(20), 'en': 'Name', 'size': 120},
                                 'new_price': {'type': FLOAT, 'en': 'Latest Price', 'size': 70},
                                 'change_rate': {'type': FLOAT, 'en': 'Change Rate', 'size': 70},
                                 'ups_downs': {'type': FLOAT, 'en': 'Change Amount', 'size': 70},
                                 'volume': {'type': BIGINT, 'en': 'Volume', 'size': 90},
                                 'deal_amount': {'type': BIGINT, 'en': 'Deal Amount', 'size': 100},
                                 'open_price': {'type': FLOAT, 'en': 'Opening Price', 'size': 70},
                                 'high_price': {'type': FLOAT, 'en': 'Highest Price', 'size': 70},
                                 'low_price': {'type': FLOAT, 'en': 'Lowest Price', 'size': 70},
                                 'pre_close_price': {'type': FLOAT, 'en': 'Previous Close Price', 'size': 70},
                                 'turnoverrate': {'type': FLOAT, 'en': 'Turnover Rate', 'size': 70},
                                 'total_market_cap': {'type': BIGINT, 'en': 'Total Market Cap', 'size': 120},
                                 'free_cap': {'type': BIGINT, 'en': 'Free Market Cap', 'size': 120}}}

TABLE_CN_STOCK_SPOT = {'name': 'cn_stock_spot', 'en': 'Daily Stock Data',
                       'columns': {'date': {'type': DATE, 'en': 'Date', 'size': 0},
                                   'code': {'type': NVARCHAR(6), 'en': 'Code', 'size': 60},
                                   'name': {'type': NVARCHAR(20), 'en': 'Name', 'size': 70},
                                   'new_price': {'type': FLOAT, 'en': 'Latest Price', 'size': 70},
                                   'change_rate': {'type': FLOAT, 'en': 'Change Rate', 'size': 70},
                                   'ups_downs': {'type': FLOAT, 'en': 'Change Amount', 'size': 70},
                                   'volume': {'type': BIGINT, 'en': 'Volume', 'size': 90},
                                   'deal_amount': {'type': BIGINT, 'en': 'Deal Amount', 'size': 100},
                                   'amplitude': {'type': FLOAT, 'en': 'Amplitude', 'size': 70},
                                   'volume_ratio': {'type': FLOAT, 'en': 'Volume Ratio', 'size': 70},
                                   'turnoverrate': {'type': FLOAT, 'en': 'Turnover Rate', 'size': 70},
                                   'open_price': {'type': FLOAT, 'en': 'Opening Price', 'size': 70},
                                   'high_price': {'type': FLOAT, 'en': 'Highest Price', 'size': 70},
                                   'low_price': {'type': FLOAT, 'en': 'Lowest Price', 'size': 70},
                                   'pre_close_price': {'type': FLOAT, 'en': 'Previous Close Price', 'size': 70},
                                   'speed_increase': {'type': FLOAT, 'en': 'Speed of Increase', 'size': 70},
                                   'speed_increase_5': {'type': FLOAT, 'en': '5-Minute Change', 'size': 70},
                                   'speed_increase_60': {'type': FLOAT, 'en': '60-Day Change Rate', 'size': 70},
                                   'speed_increase_all': {'type': FLOAT, 'en': 'Year-to-Date Change Rate', 'size': 70},
                                   'dtsyl': {'type': FLOAT, 'en': 'Dynamic Price-Earnings Ratio', 'size': 70},
                                   'pe9': {'type': FLOAT, 'en': 'TTM Price-Earnings Ratio', 'size': 70},
                                   'pe': {'type': FLOAT, 'en': 'Static Price-Earnings Ratio', 'size': 70},
                                   'pbnewmrq': {'type': FLOAT, 'en': 'Price-to-Book Ratio', 'size': 70},
                                   'basic_eps': {'type': FLOAT, 'en': 'Earnings Per Share', 'size': 70},
                                   'bvps': {'type': FLOAT, 'en': 'Net Asset Value Per Share', 'size': 70},
                                   'per_capital_reserve': {'type': FLOAT, 'en': 'Per Share Capital Reserve', 'size': 70},
                                   'per_unassign_profit': {'type': FLOAT, 'en': 'Per Share Undistributed Profit', 'size': 70},
                                   'roe_weight': {'type': FLOAT, 'en': 'Weighted ROE', 'size': 70},
                                   'sale_gpr': {'type': FLOAT, 'en': 'Gross Profit Margin', 'size': 70},
                                   'debt_asset_ratio': {'type': FLOAT, 'en': 'Debt-to-Asset Ratio', 'size': 70},
                                   'total_operate_income': {'type': BIGINT, 'en': 'Operating Revenue', 'size': 120},
                                   'toi_yoy_ratio': {'type': FLOAT, 'en': 'YoY Growth in Operating Revenue', 'size': 70},
                                   'parent_netprofit': {'type': BIGINT, 'en': 'Net Profit Attributable to Parent Company', 'size': 110},
                                   'netprofit_yoy_ratio': {'type': FLOAT, 'en': 'YoY Growth in Net Profit', 'size': 70},
                                   'report_date': {'type': DATE, 'en': 'Reporting Period', 'size': 110},
                                   'total_shares': {'type': BIGINT, 'en': 'Total Shares', 'size': 120},
                                   'free_shares': {'type': BIGINT, 'en': 'Circulating Shares', 'size': 120},
                                   'total_market_cap': {'type': BIGINT, 'en': 'Total Market Cap', 'size': 120},
                                   'free_cap': {'type': BIGINT, 'en': 'Free Market Cap', 'size': 120},
                                   'industry': {'type': NVARCHAR(20), 'en': 'Industry', 'size': 100},
                                   'listing_date': {'type': DATE, 'en': 'Listing Date', 'size': 110}}}

TABLE_CN_STOCK_SPOT_BUY = {'name': 'cn_stock_spot_buy', 'en': 'Fundamental Stock Selection',
                           'columns': TABLE_CN_STOCK_SPOT['columns'].copy()}

CN_STOCK_FUND_FLOW = ({'name': 'stock_individual_fund_flow_rank', 'en': 'Today',
                       'columns': {'code': {'type': NVARCHAR(6), 'en': 'Code', 'size': 60},
                                   'name': {'type': NVARCHAR(20), 'en': 'Name', 'size': 70},
                                   'new_price': {'type': FLOAT, 'en': 'Latest Price', 'size': 70},
                                   'change_rate': {'type': FLOAT, 'en': 'Today’s Change Rate', 'size': 70},
                                   'fund_amount': {'type': BIGINT, 'en': 'Today’s Net Fund Inflow', 'size': 100},
                                   'fund_rate': {'type': FLOAT, 'en': 'Today’s Fund Inflow Percentage', 'size': 70},
                                   'fund_amount_super': {'type': BIGINT, 'en': 'Today’s Net Super Large Orders', 'size': 100},
                                   'fund_rate_super': {'type': FLOAT, 'en': 'Today’s Super Large Orders Percentage', 'size': 70},
                                   'fund_amount_large': {'type': BIGINT, 'en': 'Today’s Net Large Orders', 'size': 100},
                                   'fund_rate_large': {'type': FLOAT, 'en': 'Today’s Large Orders Percentage', 'size': 70},
                                   'fund_amount_medium': {'type': BIGINT, 'en': 'Today’s Net Medium Orders', 'size': 100},
                                   'fund_rate_medium': {'type': FLOAT, 'en': 'Today’s Medium Orders Percentage', 'size': 70},
                                   'fund_amount_small': {'type': BIGINT, 'en': 'Today’s Net Small Orders', 'size': 100},
                                   'fund_rate_small': {'type': FLOAT, 'en': 'Today’s Small Orders Percentage', 'size': 70}}},
                      {'name': 'stock_individual_fund_flow_rank', 'en': '3-Day',
                       'columns': {'code': {'type': NVARCHAR(6), 'en': 'Code', 'size': 60},
                                   'name': {'type': NVARCHAR(20), 'en': 'Name', 'size': 70},
                                   'new_price': {'type': FLOAT, 'en': 'Latest Price', 'size': 70},
                                   'change_rate_3': {'type': FLOAT, 'en': '3-Day Change Rate', 'size': 70},
                                   'fund_amount_3': {'type': BIGINT, 'en': '3-Day Net Fund Inflow', 'size': 100},
                                   'fund_rate_3': {'type': FLOAT, 'en': '3-Day Fund Inflow Percentage', 'size': 70},
                                   'fund_amount_super_3': {'type': BIGINT, 'en': '3-Day Net Super Large Orders', 'size': 100},
                                   'fund_rate_super_3': {'type': FLOAT, 'en': '3-Day Super Large Orders Percentage', 'size': 70},
                                   'fund_amount_large_3': {'type': BIGINT, 'en': '3-Day Net Large Orders', 'size': 100},
                                   'fund_rate_large_3': {'type': FLOAT, 'en': '3-Day Large Orders Percentage', 'size': 70},
                                   'fund_amount_medium_3': {'type': BIGINT, 'en': '3-Day Net Medium Orders', 'size': 100},
                                   'fund_rate_medium_3': {'type': FLOAT, 'en': '3-Day Medium Orders Percentage', 'size': 70},
                                   'fund_amount_small_3': {'type': BIGINT, 'en': '3-Day Net Small Orders', 'size': 100},
                                   'fund_rate_small_3': {'type': FLOAT, 'en': '3-Day Small Orders Percentage', 'size': 70}}},
                      {'name': 'stock_individual_fund_flow_rank', 'en': '5-Day',
                       'columns': {'code': {'type': NVARCHAR(6), 'en': 'Code', 'size': 60},
                                   'name': {'type': NVARCHAR(20), 'en': 'Name', 'size': 70},
                                   'new_price': {'type': FLOAT, 'en': 'Latest Price', 'size': 70},
                                   'change_rate_5': {'type': FLOAT, 'en': '5-Day Change Rate', 'size': 70},
                                   'fund_amount_5': {'type': BIGINT, 'en': '5-Day Net Fund Inflow', 'size': 100},
                                   'fund_rate_5': {'type': FLOAT, 'en': '5-Day Fund Inflow Percentage', 'size': 70},
                                   'fund_amount_super_5': {'type': BIGINT, 'en': '5-Day Net Super Large Orders', 'size': 100},
                                   'fund_rate_super_5': {'type': FLOAT, 'en': '5-Day Super Large Orders Percentage', 'size': 70},
                                   'fund_amount_large_5': {'type': BIGINT, 'en': '5-Day Net Large Orders', 'size': 100},
                                   'fund_rate_large_5': {'type': FLOAT, 'en': '5-Day Large Orders Percentage', 'size': 70},
                                   'fund_amount_medium_5': {'type': BIGINT, 'en': '5-Day Net Medium Orders', 'size': 100},
                                   'fund_rate_medium_5': {'type': FLOAT, 'en': '5-Day Medium Orders Percentage', 'size': 70},
                                   'fund_amount_small_5': {'type': BIGINT, 'en': '5-Day Net Small Orders', 'size': 100},
                                   'fund_rate_small_5': {'type': FLOAT, 'en': '5-Day Small Orders Percentage', 'size': 70}}},
                      {'name': 'stock_individual_fund_flow_rank', 'en': '10-Day',
                       'columns': {'code': {'type': NVARCHAR(6), 'en': 'Code', 'size': 60},
                                   'name': {'type': NVARCHAR(20), 'en': 'Name', 'size': 70},
                                   'new_price': {'type': FLOAT, 'en': 'Latest Price', 'size': 70},
                                   'change_rate_10': {'type': FLOAT, 'en': '10-Day Change Rate', 'size': 70},
                                   'fund_amount_10': {'type': BIGINT, 'en': '10-Day Net Fund Inflow', 'size': 100},
                                   'fund_rate_10': {'type': FLOAT, 'en': '10-Day Fund Inflow Percentage', 'size': 70},
                                   'fund_amount_super_10': {'type': BIGINT, 'en': '10-Day Net Super Large Orders', 'size': 100},
                                   'fund_rate_super_10': {'type': FLOAT, 'en': '10-Day Super Large Orders Percentage', 'size': 70},
                                   'fund_amount_large_10': {'type': BIGINT, 'en': '10-Day Net Large Orders', 'size': 100},
                                   'fund_rate_large_10': {'type': FLOAT, 'en': '10-Day Large Orders Percentage', 'size': 70},
                                   'fund_amount_medium_10': {'type': BIGINT, 'en': '10-Day Net Medium Orders', 'size': 100},
                                   'fund_rate_medium_10': {'type': FLOAT, 'en': '10-Day Medium Orders Percentage', 'size': 70},
                                   'fund_amount_small_10': {'type': BIGINT, 'en': '10-Day Net Small Orders', 'size': 100},
                                   'fund_rate_small_10': {'type': FLOAT, 'en': '10-Day Small Orders Percentage', 'size': 70}}}})

TABLE_CN_STOCK_FUND_FLOW = {'name': 'cn_stock_fund_flow', 'en': 'Stock Fund Flow',
                            'columns': {'date': {'type': DATE, 'en': 'Date', 'size': 0}}}
for cf in CN_STOCK_FUND_FLOW:
    TABLE_CN_STOCK_FUND_FLOW['columns'].update(cf['columns'].copy())

CN_STOCK_SECTOR_FUND_FLOW = (('Industry Fund Flow', 'Concept Fund Flow'),
                             ({'name': 'stock_sector_fund_flow_rank', 'en': 'Today',
                              'columns': {'name': {'type': NVARCHAR(20), 'en': 'Name', 'size': 70},
                                          'change_rate': {'type': FLOAT, 'en': 'Today’s Change Rate', 'size': 70},
                                          'fund_amount': {'type': BIGINT, 'en': 'Today’s Net Fund Inflow', 'size': 100},
                                          'fund_rate': {'type': FLOAT, 'en': 'Today’s Fund Inflow Percentage', 'size': 70},
                                          'fund_amount_super': {'type': BIGINT, 'en': 'Today’s Net Super Large Orders', 'size': 100},
                                          'fund_rate_super': {'type': FLOAT, 'en': 'Today’s Super Large Orders Percentage', 'size': 70},
                                          'fund_amount_large': {'type': BIGINT, 'en': 'Today’s Net Large Orders', 'size': 100},
                                          'fund_rate_large': {'type': FLOAT, 'en': 'Today’s Large Orders Percentage', 'size': 70},
                                          'fund_amount_medium': {'type': BIGINT, 'en': 'Today’s Net Medium Orders', 'size': 100},
                                          'fund_rate_medium': {'type': FLOAT, 'en': 'Today’s Medium Orders Percentage', 'size': 70},
                                          'fund_amount_small': {'type': BIGINT, 'en': 'Today’s Net Small Orders', 'size': 100},
                                          'fund_rate_small': {'type': FLOAT, 'en': 'Today’s Small Orders Percentage', 'size': 70},
                                          'stock_name': {'type': NVARCHAR(20), 'en': 'Today’s Largest Fund Inflow Stock', 'size': 70}}}})


TABLE_CN_STOCK_FUND_FLOW_INDUSTRY = {'name': 'cn_stock_fund_flow_industry', 'en': 'Industry Fund Flow',
                                     'columns': {'date': {'type': DATE, 'en': 'Date', 'size': 0}}}
for cf in CN_STOCK_SECTOR_FUND_FLOW[1]:
    TABLE_CN_STOCK_FUND_FLOW_INDUSTRY['columns'].update(cf['columns'].copy())

TABLE_CN_STOCK_FUND_FLOW_CONCEPT = {'name': 'cn_stock_fund_flow_concept', 'en': 'Concept Fund Flow',
                                    'columns': {'date': {'type': DATE, 'en': 'Date', 'size': 0}}}
for cf in CN_STOCK_SECTOR_FUND_FLOW[1]:
    TABLE_CN_STOCK_FUND_FLOW_CONCEPT['columns'].update(cf['columns'].copy())

TABLE_CN_STOCK_BONUS = {'name': 'cn_stock_bonus', 'en': 'Stock Bonus Distribution',
                        'columns': {'date': {'type': DATE, 'en': 'Date', 'size': 0},
                                    'code': {'type': NVARCHAR(6), 'en': 'Code', 'size': 60},
                                    'name': {'type': NVARCHAR(20), 'en': 'Name', 'size': 70},
                                    'convertible_total_rate': {'type': FLOAT, 'en': 'Convertible Total Ratio', 'size': 70},
                                    'convertible_rate': {'type': FLOAT, 'en': 'Convertible Ratio', 'size': 70},
                                    'convertible_transfer_rate': {'type': FLOAT, 'en': 'Convertible Transfer Ratio', 'size': 70},
                                    'bonusaward_rate': {'type': FLOAT, 'en': 'Cash Dividend Ratio', 'size': 70},
                                    'bonusaward_yield': {'type': FLOAT, 'en': 'Cash Dividend Yield', 'size': 70},
                                    'basic_eps': {'type': FLOAT, 'en': 'Earnings Per Share', 'size': 70},
                                    'bvps': {'type': FLOAT, 'en': 'Book Value Per Share', 'size': 70},
                                    'per_capital_reserve': {'type': FLOAT, 'en': 'Capital Reserve Per Share', 'size': 70},
                                    'per_unassign_profit': {'type': FLOAT, 'en': 'Unassigned Profit Per Share', 'size': 70},
                                    'netprofit_yoy_ratio': {'type': FLOAT, 'en': 'YoY Net Profit Growth', 'size': 70},
                                    'total_shares': {'type': BIGINT, 'en': 'Total Shares', 'size': 120},
                                    'plan_date': {'type': DATE, 'en': 'Plan Announcement Date', 'size': 110},
                                    'record_date': {'type': DATE, 'en': 'Equity Record Date', 'size': 110},
                                    'ex_dividend_date': {'type': DATE, 'en': 'Ex-dividend Date', 'size': 110},
                                    'progress': {'type': NVARCHAR(50), 'en': 'Plan Progress', 'size': 100},
                                    'report_date': {'type': DATE, 'en': 'Latest Announcement Date', 'size': 110}}}

TABLE_CN_STOCK_TOP = {'name': 'cn_stock_top', 'en': 'Stock Leaderboard',
                      'columns': {'date': {'type': DATE, 'en': 'Date', 'size': 0},
                                  'code': {'type': NVARCHAR(6), 'en': 'Code', 'size': 60},
                                  'name': {'type': NVARCHAR(20), 'en': 'Name', 'size': 70},
                                  'ranking_times': {'type': FLOAT, 'en': 'Number of Rankings', 'size': 70},
                                  'sum_buy': {'type': FLOAT, 'en': 'Total Buy Amount', 'size': 100},
                                  'sum_sell': {'type': FLOAT, 'en': 'Total Sell Amount', 'size': 100},
                                  'net_amount': {'type': FLOAT, 'en': 'Net Amount', 'size': 100},
                                  'buy_seat': {'type': FLOAT, 'en': 'Number of Buy Seats', 'size': 100},
                                  'sell_seat': {'type': FLOAT, 'en': 'Number of Sell Seats', 'size': 100}}}

TABLE_CN_STOCK_BLOCKTRADE = {'name': 'cn_stock_blocktrade', 'en': 'Stock Block Trade',
                             'columns': {'date': {'type': DATE, 'en': 'Date', 'size': 0},
                                         'code': {'type': NVARCHAR(6), 'en': 'Code', 'size': 60},
                                         'name': {'type': NVARCHAR(20), 'en': 'Name', 'size': 70},
                                         'new_price': {'type': FLOAT, 'en': 'Closing Price', 'size': 70},
                                         'change_rate': {'type': FLOAT, 'en': 'Change Rate', 'size': 70},
                                         'average_price': {'type': FLOAT, 'en': 'Average Price', 'size': 70},
                                         'overflow_rate': {'type': FLOAT, 'en': 'Overflow Rate', 'size': 120},
                                         'trade_number': {'type': FLOAT, 'en': 'Number of Trades', 'size': 70},
                                         'sum_volume': {'type': FLOAT, 'en': 'Total Volume', 'size': 100},
                                         'sum_turnover': {'type': FLOAT, 'en': 'Total Turnover', 'size': 100},
                                         'turnover_market_rate': {'type': FLOAT, 'en': 'Turnover Percentage of Market Value',
                                                                  'size': 120}}}

CN_STOCK_HIST_DATA = {'name': 'fund_etf_hist_em', 'en': 'Fund Historical Data Database',
                      'columns': {'date': {'type': DATE, 'en': 'Date'},
                                  'open': {'type': FLOAT, 'en': 'Open'},
                                  'close': {'type': FLOAT, 'en': 'Close'},
                                  'high': {'type': FLOAT, 'en': 'High'},
                                  'low': {'type': FLOAT, 'en': 'Low'},
                                  'volume': {'type': FLOAT, 'en': 'Volume'},
                                  'amount': {'type': FLOAT, 'en': 'Amount'},
                                  'amplitude': {'type': FLOAT, 'en': 'Amplitude'},
                                  'quote_change': {'type': FLOAT, 'en': 'Change Rate'},
                                  'ups_downs': {'type': FLOAT, 'en': 'Change Amount'},
                                  'turnover': {'type': FLOAT, 'en': 'Turnover Rate'}}}

TABLE_CN_STOCK_FOREIGN_KEY = {'name': 'cn_stock_foreign_key', 'en': 'Stock Foreign Key',
                              'columns': {'date': {'type': DATE, 'en': 'Date', 'size': 0},
                                          'code': {'type': NVARCHAR(6), 'en': 'Code', 'size': 60},
                                          'name': {'type': NVARCHAR(20), 'en': 'Name', 'size': 70}}}

TABLE_CN_STOCK_BACKTEST_DATA = {'name': 'cn_stock_backtest_data', 'en': 'Stock Backtest Data',
                                'columns': {'rate_%s' % i: {'type': FLOAT, 'en': '%s-Day Yield Rate' % i, 'size': 100} for i in
                                            range(1, RATE_FIELDS_COUNT + 1, 1)}}

STOCK_STATS_DATA = {'name': 'calculate_indicator', 'en': 'Stock Statistics/Indicator Calculation Assistant Library',
                    'columns': {'close': {'type': FLOAT, 'en': 'Price', 'size': 0},
                                'macd': {'type': FLOAT, 'en': 'dif', 'size': 70},
                                'macds': {'type': FLOAT, 'en': 'macd', 'size': 70},
                                'macdh': {'type': FLOAT, 'en': 'histogram', 'size': 70},
                                'kdjk': {'type': FLOAT, 'en': 'kdjk', 'size': 70},
                                'kdjd': {'type': FLOAT, 'en': 'kdjd', 'size': 70},
                                'kdjj': {'type': FLOAT, 'en': 'kdjj', 'size': 70},
                                'boll_ub': {'type': FLOAT, 'en': 'boll upper band', 'size': 70},
                                'boll': {'type': FLOAT, 'en': 'boll', 'size': 70},
                                'boll_lb': {'type': FLOAT, 'en': 'boll lower band', 'size': 70},
                                'trix': {'type': FLOAT, 'en': 'trix', 'size': 70},
                                'trix_20_sma': {'type': FLOAT, 'en': 'trma', 'size': 70},
                                'tema': {'type': FLOAT, 'en': 'tema', 'size': 70},
                                'cr': {'type': FLOAT, 'en': 'cr', 'size': 70},
                                'cr-ma1': {'type': FLOAT, 'en': 'cr-ma1', 'size': 70},
                                'cr-ma2': {'type': FLOAT, 'en': 'cr-ma2', 'size': 70},
                                'cr-ma3': {'type': FLOAT, 'en': 'cr-ma3', 'size': 70},
                                'rsi_6': {'type': FLOAT, 'en': 'rsi_6', 'size': 70},
                                'rsi_12': {'type': FLOAT, 'en': 'rsi_12', 'size': 70},
                                'rsi': {'type': FLOAT, 'en': 'rsi', 'size': 70},
                                'rsi_24': {'type': FLOAT, 'en': 'rsi_24', 'size': 70},
                                'vr': {'type': FLOAT, 'en': 'vr', 'size': 70},
                                'vr_6_sma': {'type': FLOAT, 'en': 'mavr', 'size': 70},
                                'roc': {'type': FLOAT, 'en': 'roc', 'size': 70},
                                'rocma': {'type': FLOAT, 'en': 'rocma', 'size': 70},
                                'rocema': {'type': FLOAT, 'en': 'rocema', 'size': 70},
                                'pdi': {'type': FLOAT, 'en': 'pdi', 'size': 70},
                                'mdi': {'type': FLOAT, 'en': 'mdi', 'size': 70},
                                'dx': {'type': FLOAT, 'en': 'dx', 'size': 70},
                                'adx': {'type': FLOAT, 'en': 'adx', 'size': 70},
                                'adxr': {'type': FLOAT, 'en': 'adxr', 'size': 70},
                                'wr_6': {'type': FLOAT, 'en': 'wr_6', 'size': 70},
                                'wr_10': {'type': FLOAT, 'en': 'wr_10', 'size': 70},
                                'wr_14': {'type': FLOAT, 'en': 'wr_14', 'size': 70},
                                'cci': {'type': FLOAT, 'en': 'cci', 'size': 70},
                                'cci_84': {'type': FLOAT, 'en': 'cci_84', 'size': 70},
                                'tr': {'type': FLOAT, 'en': 'tr', 'size': 70},
                                'atr': {'type': FLOAT, 'en': 'atr', 'size': 70},
                                'dma': {'type': FLOAT, 'en': 'dma', 'size': 70},
                                'dma_10_sma': {'type': FLOAT, 'en': 'ama', 'size': 70},
                                'obv': {'type': FLOAT, 'en': 'obv', 'size': 70},
                                'sar': {'type': FLOAT, 'en': 'sar', 'size': 70},
                                'psy': {'type': FLOAT, 'en': 'psy', 'size': 70},
                                'psyma': {'type': FLOAT, 'en': 'psyma', 'size': 70},
                                'br': {'type': FLOAT, 'en': 'br', 'size': 70},
                                'ar': {'type': FLOAT, 'en': 'ar', 'size': 70},
                                'emv': {'type': FLOAT, 'en': 'emv', 'size': 70},
                                'emva': {'type': FLOAT, 'en': 'emva', 'size': 70},
                                'bias': {'type': FLOAT, 'en': 'bias', 'size': 70},
                                'mfi': {'type': FLOAT, 'en': 'mfi', 'size': 70},
                                'mfisma': {'type': FLOAT, 'en': 'mfisma', 'size': 70},
                                'vwma': {'type': FLOAT, 'en': 'vwma', 'size': 70},
                                'mvwma': {'type': FLOAT, 'en': 'mvwma', 'size': 70},
                                'ppo': {'type': FLOAT, 'en': 'ppo', 'size': 70},
                                'ppos': {'type': FLOAT, 'en': 'ppos', 'size': 70},
                                'ppoh': {'type': FLOAT, 'en': 'ppoh', 'size': 70},
                                'wt1': {'type': FLOAT, 'en': 'wt1', 'size': 70},
                                'wt2': {'type': FLOAT, 'en': 'wt2', 'size': 70},
                                'supertrend_ub': {'type': FLOAT, 'en': 'supertrend upper band', 'size': 70},
                                'supertrend': {'type': FLOAT, 'en': 'supertrend', 'size': 70},
                                'supertrend_lb': {'type': FLOAT, 'en': 'supertrend lower band', 'size': 70},
                                'dpo': {'type': FLOAT, 'en': 'dpo', 'size': 70},
                                'madpo': {'type': FLOAT, 'en': 'madpo', 'size': 70},
                                'vhf': {'type': FLOAT, 'en': 'vhf', 'size': 70},
                                'rvi': {'type': FLOAT, 'en': 'rvi', 'size': 70},
                                'rvis': {'type': FLOAT, 'en': 'rvis', 'size': 70},
                                'fi': {'type': FLOAT, 'en': 'fi', 'size': 70},
                                'force_2': {'type': FLOAT, 'en': 'force_2', 'size': 70},
                                'force_13': {'type': FLOAT, 'en': 'force_13', 'size': 70},
                                'ene_ue': {'type': FLOAT, 'en': 'ene upper band', 'size': 70},
                                'ene': {'type': FLOAT, 'en': 'ene', 'size': 70},
                                'ene_le': {'type': FLOAT, 'en': 'ene lower band', 'size': 70},
                                'stochrsi_k': {'type': FLOAT, 'en': 'stochrsi_k', 'size': 70},
                                'stochrsi_d': {'type': FLOAT, 'en': 'stochrsi_d', 'size': 70}}}

TABLE_CN_STOCK_INDICATORS = {'name': 'cn_stock_indicators', 'en': 'Stock Indicator Data',
                             'columns': TABLE_CN_STOCK_FOREIGN_KEY['columns'].copy()}
TABLE_CN_STOCK_INDICATORS['columns'].update(STOCK_STATS_DATA['columns'])

_tmp_columns = TABLE_CN_STOCK_FOREIGN_KEY['columns'].copy()
_tmp_columns.update(TABLE_CN_STOCK_BACKTEST_DATA['columns'])

TABLE_CN_STOCK_INDICATORS_BUY = {'name': 'cn_stock_indicators_buy', 'en': 'Stock Indicators Buy',
                                 'columns': _tmp_columns}

TABLE_CN_STOCK_INDICATORS_SELL = {'name': 'cn_stock_indicators_sell', 'en': 'Stock Indicators Sell',
                                  'columns': _tmp_columns}

TABLE_CN_STOCK_STRATEGIES = [
    {'name': 'cn_stock_strategy_enter', 'en': 'Volume Increase', 'size': 70, 'func': enter.check_volume,
     'columns': _tmp_columns},
    {'name': 'cn_stock_strategy_keep_increasing', 'en': 'Moving Average Bullish', 'size': 70, 'func': keep_increasing.check,
     'columns': _tmp_columns},
    {'name': 'cn_stock_strategy_parking_apron', 'en': 'Parking Apron', 'size': 70, 'func': parking_apron.check,
     'columns': _tmp_columns},
    {'name': 'cn_stock_strategy_backtrace_ma250', 'en': 'Yearly Line Backtrace', 'size': 70, 'func': backtrace_ma250.check,
     'columns': _tmp_columns},
    {'name': 'cn_stock_strategy_breakthrough_platform', 'en': 'Platform Breakthrough', 'size': 70,
     'func': breakthrough_platform.check,
     'columns': _tmp_columns},
    {'name': 'cn_stock_strategy_low_backtrace_increase', 'en': 'No Major Retracement', 'size': 70,
     'func': low_backtrace_increase.check,
     'columns': _tmp_columns},
    {'name': 'cn_stock_strategy_turtle_trade', 'en': 'Turtle Trading Rules', 'size': 70, 'func': turtle_trade.check_enter,
     'columns': _tmp_columns},
    {'name': 'cn_stock_strategy_high_tight_flag', 'en': 'High and Tight Flag', 'size': 70,
     'func': high_tight_flag.check_high_tight,
     'columns': _tmp_columns},
    {'name': 'cn_stock_strategy_climax_limitdown', 'en': 'Volume Decrease Limit Down', 'size': 70, 'func': climax_limitdown.check,
     'columns': _tmp_columns},
    {'name': 'cn_stock_strategy_low_atr', 'en': 'Low ATR Growth', 'size': 70, 'func': low_atr.check_low_increase,
     'columns': _tmp_columns}
]

STOCK_KLINE_PATTERN_DATA = {'name': 'cn_stock_pattern_recognitions', 'en': 'K-line Patterns',
                            'columns': {
                                'tow_crows': {'type': SmallInteger, 'en': 'Two Crows', 'size': 70, 'func': tl.CDL2CROWS},
                                'upside_gap_two_crows': {'type': SmallInteger, 'en': 'Upside Gap Two Crows', 'size': 70,
                                                         'func': tl.CDLUPSIDEGAP2CROWS},
                                'three_black_crows': {'type': SmallInteger, 'en': 'Three Black Crows', 'size': 70,
                                                      'func': tl.CDL3BLACKCROWS},
                                'identical_three_crows': {'type': SmallInteger, 'en': 'Identical Three Crows', 'size': 70,
                                                          'func': tl.CDLIDENTICAL3CROWS},
                                'three_line_strike': {'type': SmallInteger, 'en': 'Three Line Strike', 'size': 70,
                                                      'func': tl.CDL3LINESTRIKE},
                                'dark_cloud_cover': {'type': SmallInteger, 'en': 'Dark Cloud Cover', 'size': 70,
                                                     'func': tl.CDLDARKCLOUDCOVER},
                                'evening_doji_star': {'type': SmallInteger, 'en': 'Evening Doji Star', 'size': 70,
                                                      'func': tl.CDLEVENINGDOJISTAR},
                                'doji_Star': {'type': SmallInteger, 'en': 'Doji Star', 'size': 70, 'func': tl.CDLDOJISTAR},
                                'hanging_man': {'type': SmallInteger, 'en': 'Hanging Man', 'size': 70,
                                                'func': tl.CDLHANGINGMAN},
                                'hikkake_pattern': {'type': SmallInteger, 'en': 'Hikkake Pattern', 'size': 70,
                                                    'func': tl.CDLHIKKAKE},
                                'modified_hikkake_pattern': {'type': SmallInteger, 'en': 'Modified Hikkake Pattern', 'size': 70,
                                                             'func': tl.CDLHIKKAKEMOD},
                                'in_neck_pattern': {'type': SmallInteger, 'en': 'In Neck Pattern', 'size': 70,
                                                    'func': tl.CDLINNECK},
                                'on_neck_pattern': {'type': SmallInteger, 'en': 'On Neck Pattern', 'size': 70,
                                                    'func': tl.CDLONNECK},
                                'thrusting_pattern': {'type': SmallInteger, 'en': 'Thrusting Pattern', 'size': 70,
                                                      'func': tl.CDLTHRUSTING},
                                'shooting_star': {'type': SmallInteger, 'en': 'Shooting Star', 'size': 70,
                                                  'func': tl.CDLSHOOTINGSTAR},
                                'stalled_pattern': {'type': SmallInteger, 'en': 'Stalled Pattern', 'size': 70,
                                                    'func': tl.CDLSTALLEDPATTERN},
                                'advance_block': {'type': SmallInteger, 'en': 'Advance Block', 'size': 70,
                                                  'func': tl.CDLADVANCEBLOCK},
                                'high_wave_candle': {'type': SmallInteger, 'en': 'High Wave Candle', 'size': 70,
                                                     'func': tl.CDLHIGHWAVE},
                                'engulfing_pattern': {'type': SmallInteger, 'en': 'Engulfing Pattern', 'size': 70,
                                                      'func': tl.CDLENGULFING},
                                'abandoned_baby': {'type': SmallInteger, 'en': 'Abandoned Baby', 'size': 70,
                                                   'func': tl.CDLABANDONEDBABY},
                                'closing_marubozu': {'type': SmallInteger, 'en': 'Closing Marubozu', 'size': 70,
                                                     'func': tl.CDLCLOSINGMARUBOZU},
                                'doji': {'type': SmallInteger, 'en': 'Doji', 'size': 70, 'func': tl.CDLDOJI},
                                'up_down_gap': {'type': SmallInteger, 'en': 'Upside/Downside Gap', 'size': 70,
                                                'func': tl.CDLGAPSIDESIDEWHITE},
                                'long_legged_doji': {'type': SmallInteger, 'en': 'Long-Legged Doji', 'size': 70,
                                                     'func': tl.CDLLONGLEGGEDDOJI},
                                'rickshaw_man': {'type': SmallInteger, 'en': 'Rickshaw Man', 'size': 70,
                                                 'func': tl.CDLRICKSHAWMAN},
                                'marubozu': {'type': SmallInteger, 'en': 'Marubozu', 'size': 70,
                                             'func': tl.CDLMARUBOZU},
                                'three_inside_up_down': {'type': SmallInteger, 'en': 'Three Inside Up/Down', 'size': 70,
                                                         'func': tl.CDL3INSIDE},
                                'three_outside_up_down': {'type': SmallInteger, 'en': 'Three Outside Up/Down', 'size': 70,
                                                          'func': tl.CDL3OUTSIDE},
                                'three_stars_in_the_south': {'type': SmallInteger, 'en': 'Three Stars in the South', 'size': 70,
                                                             'func': tl.CDL3STARSINSOUTH},
                                'three_white_soldiers': {'type': SmallInteger, 'en': 'Three White Soldiers', 'size': 70,
                                                         'func': tl.CDL3WHITESOLDIERS},
                                'belt_hold': {'type': SmallInteger, 'en': 'Belt Hold', 'size': 70,
                                              'func': tl.CDLBELTHOLD},
                                'breakaway': {'type': SmallInteger, 'en': 'Breakaway', 'size': 70, 'func': tl.CDLBREAKAWAY},
                                'concealing_baby_swallow': {'type': SmallInteger, 'en': 'Concealing Baby Swallow', 'size': 70,
                                                            'func': tl.CDLCONCEALBABYSWALL},
                                'counterattack': {'type': SmallInteger, 'en': 'Counterattack', 'size': 70,
                                                  'func': tl.CDLCOUNTERATTACK},
                                'dragonfly_doji': {'type': SmallInteger, 'en': 'Dragonfly Doji', 'size': 70,
                                                   'func': tl.CDLDRAGONFLYDOJI},
                                'evening_star': {'type': SmallInteger, 'en': 'Evening Star', 'size': 70,
                                                 'func': tl.CDLEVENINGSTAR},
                                'gravestone_doji': {'type': SmallInteger, 'en': 'Gravestone Doji', 'size': 70,
                                                    'func': tl.CDLGRAVESTONEDOJI},
                                'hammer': {'type': SmallInteger, 'en': 'Hammer', 'size': 70, 'func': tl.CDLHAMMER},
                                'harami_pattern': {'type': SmallInteger, 'en': 'Harami Pattern', 'size': 70,
                                                   'func': tl.CDLHARAMI},
                                'harami_cross_pattern': {'type': SmallInteger, 'en': 'Harami Cross Pattern', 'size': 70,
                                                         'func': tl.CDLHARAMICROSS},
                                'homing_pigeon': {'type': SmallInteger, 'en': 'Homing Pigeon', 'size': 70,
                                                  'func': tl.CDLHOMINGPIGEON},
                                'inverted_hammer': {'type': SmallInteger, 'en': 'Inverted Hammer', 'size': 70,
                                                    'func': tl.CDLINVERTEDHAMMER},
                                'kicking': {'type': SmallInteger, 'en': 'Kicking', 'size': 70, 'func': tl.CDLKICKING},
                                'kicking_bull_bear': {'type': SmallInteger, 'en': 'Kicking by Length', 'size': 70,
                                                      'func': tl.CDLKICKINGBYLENGTH},
                                'ladder_bottom': {'type': SmallInteger, 'en': 'Ladder Bottom', 'size': 70,
                                                  'func': tl.CDLLADDERBOTTOM},
                                'long_line_candle': {'type': SmallInteger, 'en': 'Long Line Candle', 'size': 70,
                                                     'func': tl.CDLLONGLINE},
                                'matching_low': {'type': SmallInteger, 'en': 'Matching Low', 'size': 70,
                                                 'func': tl.CDLMATCHINGLOW},
                                'mat_hold': {'type': SmallInteger, 'en': 'Mat Hold', 'size': 70, 'func': tl.CDLMATHOLD},
                                'morning_doji_star': {'type': SmallInteger, 'en': 'Morning Doji Star', 'size': 70,
                                                      'func': tl.CDLMORNINGDOJISTAR},
                                'morning_star': {'type': SmallInteger, 'en': 'Morning Star', 'size': 70,
                                                 'func': tl.CDLMORNINGSTAR},
                                'piercing_pattern': {'type': SmallInteger, 'en': 'Piercing Pattern', 'size': 70,
                                                     'func': tl.CDLPIERCING},
                                'rising_falling_three': {'type': SmallInteger, 'en': 'Rising/Falling Three Methods', 'size': 70,
                                                         'func': tl.CDLRISEFALL3METHODS},
                                'separating_lines': {'type': SmallInteger, 'en': 'Separating Lines', 'size': 70,
                                                     'func': tl.CDLSEPARATINGLINES},
                                'short_line_candle': {'type': SmallInteger, 'en': 'Short Line Candle', 'size': 70,
                                                      'func': tl.CDLSHORTLINE},
                                'spinning_top': {'type': SmallInteger, 'en': 'Spinning Top', 'size': 70,
                                                 'func': tl.CDLSPINNINGTOP},
                                'stick_sandwich': {'type': SmallInteger, 'en': 'Stick Sandwich', 'size': 70,
                                                   'func': tl.CDLSTICKSANDWICH},
                                'takuri': {'type': SmallInteger, 'en': 'Takuri (Testing Water)', 'size': 70, 'func': tl.CDLTAKURI},
                                'tasuki_gap': {'type': SmallInteger, 'en': 'Tasuki Gap', 'size': 70,
                                               'func': tl.CDLTASUKIGAP},
                                'tristar_pattern': {'type': SmallInteger, 'en': 'Tristar Pattern', 'size': 70,
                                                    'func': tl.CDLTRISTAR},
                                'unique_3_river': {'type': SmallInteger, 'en': 'Unique 3 River', 'size': 70,
                                                   'func': tl.CDLUNIQUE3RIVER},
                                'upside_downside_gap': {'type': SmallInteger, 'en': 'Upside/Downside Gap Three Methods', 'size': 70,
                                                        'func': tl.CDLXSIDEGAP3METHODS}}}

TABLE_CN_STOCK_KLINE_PATTERN = {'name': 'cn_stock_pattern', 'en': 'Stock K-line Patterns',
                                'columns': TABLE_CN_STOCK_FOREIGN_KEY['columns'].copy()}
TABLE_CN_STOCK_KLINE_PATTERN['columns'].update(STOCK_KLINE_PATTERN_DATA['columns'])

TABLE_CN_STOCK_SELECTION = {'name': 'cn_stock_selection', 'en': 'Comprehensive Stock Selection',
                            'columns': {'date': {'type': DATE, 'en': 'Date', 'size': 0, 'map': 'MAX_TRADE_DATE'},
                                        'code': {'type': NVARCHAR(length=6), 'en': 'Code', 'size': 60,
                                                 'map': 'SECURITY_CODE'},
                                        'name': {'type': NVARCHAR(length=20), 'en': 'Name', 'size': 70,
                                                 'map': 'SECURITY_NAME_ABBR'},
                                        'new_price': {'type': FLOAT, 'en': 'Latest Price', 'size': 70, 'map': 'NEW_PRICE'},
                                        'change_rate': {'type': FLOAT, 'en': 'Change Rate', 'size': 70,
                                                        'map': 'CHANGE_RATE'},
                                        'volume_ratio': {'type': FLOAT, 'en': 'Volume Ratio', 'size': 70,
                                                         'map': 'VOLUME_RATIO'},
                                        'high_price': {'type': FLOAT, 'en': 'Highest Price', 'size': 70, 'map': 'HIGH_PRICE'},
                                        'low_price': {'type': FLOAT, 'en': 'Lowest Price', 'size': 70, 'map': 'LOW_PRICE'},
                                        'pre_close_price': {'type': FLOAT, 'en': 'Previous Close Price', 'size': 70,
                                                            'map': 'PRE_CLOSE_PRICE'},
                                        'volume': {'type': BIGINT, 'en': 'Volume', 'size': 90, 'map': 'VOLUME'},
                                        'deal_amount': {'type': BIGINT, 'en': 'Transaction Amount', 'size': 100,
                                                        'map': 'DEAL_AMOUNT'},
                                        'turnoverrate': {'type': FLOAT, 'en': 'Turnover Rate', 'size': 70,
                                                         'map': 'TURNOVERRATE'},
                                        'listing_date': {'type': DATE, 'en': 'Listing Date', 'size': 110,
                                                         'map': 'LISTING_DATE'},
                                        'industry': {'type': NVARCHAR(length=20), 'en': 'Industry', 'size': 100,
                                                     'map': 'INDUSTRY'},
                                        'area': {'type': NVARCHAR(length=20), 'en': 'Region', 'size': 70, 'map': 'AREA'},
                                        'concept': {'type': NVARCHAR(length=255), 'en': 'Concept', 'size': 150,
                                                    'map': 'CONCEPT'},
                                        'style': {'type': NVARCHAR(length=255), 'en': 'Sector', 'size': 150,
                                                  'map': 'STYLE'},
                                        'is_hs300': {'type': NVARCHAR(length=2), 'en': 'HS300 Index', 'size': 0,
                                                     'map': 'IS_HS300'},
                                        'is_sz50': {'type': NVARCHAR(length=2), 'en': 'SZ50 Index', 'size': 0,
                                                    'map': 'IS_SZ50'},
                                        'is_zz500': {'type': NVARCHAR(length=2), 'en': 'ZZ500 Index', 'size': 0,
                                                     'map': 'IS_ZZ500'},
                                        'is_zz1000': {'type': NVARCHAR(length=2), 'en': 'ZZ1000 Index', 'size': 0,
                                                      'map': 'IS_ZZ1000'},
                                        'is_cy50': {'type': NVARCHAR(length=2), 'en': 'CY50 Index', 'size': 0,
                                                    'map': 'IS_CY50'},
                                        'pe9': {'type': FLOAT, 'en': 'P/E Ratio (TTM)', 'size': 70, 'map': 'PE9'},
                                        'pbnewmrq': {'type': FLOAT, 'en': 'P/B Ratio (MRQ)', 'size': 70, 'map': 'PBNEWMRQ'},
                                        'pettmdeducted': {'type': FLOAT, 'en': 'P/E Ratio (TTM, Excluding Extraordinary Items)',
                                                          'size': 70, 'map': 'PETTMDEDUCTED'},
                                        'ps9': {'type': FLOAT, 'en': 'P/S Ratio (TTM)', 'size': 70, 'map': 'PS9'},
                                        'pcfjyxjl9': {'type': FLOAT, 'en': 'P/CF Ratio (TTM)', 'size': 70, 'map': 'PCFJYXJL9'},
                                        'predict_pe_syear': {'type': FLOAT, 'en': 'Predicted P/E Ratio (This Year)', 'size': 70,
                                                             'map': 'PREDICT_PE_SYEAR'},
                                        'predict_pe_nyear': {'type': FLOAT, 'en': 'Predicted P/E Ratio (Next Year)', 'size': 70,
                                                             'map': 'PREDICT_PE_NYEAR'},
                                        'total_market_cap': {'type': BIGINT, 'en': 'Total Market Capitalization', 'size': 120,
                                                             'map': 'TOTAL_MARKET_CAP'},
                                        'free_cap': {'type': BIGINT, 'en': 'Circulating Market Capitalization', 'size': 120,
                                                     'map': 'FREE_CAP'},
                                        'dtsyl': {'type': FLOAT, 'en': 'Dynamic P/E Ratio', 'size': 70, 'map': 'DTSYL'},
                                        'ycpeg': {'type': FLOAT, 'en': 'Predicted PEG', 'size': 70, 'map': 'YCPEG'},
                                        'enterprise_value_multiple': {'type': FLOAT, 'en': 'Enterprise Value Multiple', 'size': 70,
                                                                      'map': 'ENTERPRISE_VALUE_MULTIPLE'},
                                        'basic_eps': {'type': FLOAT, 'en': 'Earnings Per Share', 'size': 70, 'map': 'BASIC_EPS'},
                                        'bvps': {'type': FLOAT, 'en': 'Book Value Per Share', 'size': 70, 'map': 'BVPS'},
                                        'per_netcash_operate': {'type': FLOAT, 'en': 'Operating Cash Flow Per Share', 'size': 70,
                                                                'map': 'PER_NETCASH_OPERATE'},
                                        'per_fcfe': {'type': FLOAT, 'en': 'Free Cash Flow Per Share', 'size': 70,
                                                     'map': 'PER_FCFE'},
                                        'per_capital_reserve': {'type': FLOAT, 'en': 'Capital Reserve Per Share', 'size': 70,
                                                                'map': 'PER_CAPITAL_RESERVE'},
                                        'per_unassign_profit': {'type': FLOAT, 'en': 'Unallocated Profit Per Share', 'size': 70,
                                                                'map': 'PER_UNASSIGN_PROFIT'},
                                        'per_surplus_reserve': {'type': FLOAT, 'en': 'Surplus Reserve Per Share', 'size': 70,
                                                                'map': 'PER_SURPLUS_RESERVE'},
                                        'per_retained_earning': {'type': FLOAT, 'en': 'Retained Earnings Per Share', 'size': 70,
                                                                 'map': 'PER_RETAINED_EARNING'},
                                        'parent_netprofit': {'type': BIGINT, 'en': 'Net Profit Attributable to Parent Company',
                                                             'size': 110, 'map': 'PARENT_NETPROFIT'},
                                        'deduct_netprofit': {'type': BIGINT, 'en': 'Net Profit Excluding Extraordinary Items',
                                                             'size': 110, 'map': 'DEDUCT_NETPROFIT'},
                                        'total_operate_income': {'type': BIGINT, 'en': 'Total Operating Income', 'size': 120,
                                                                 'map': 'TOTAL_OPERATE_INCOME'},
                                        'roe_weight': {'type': FLOAT, 'en': 'Return on Equity (ROE)', 'size': 70,
                                                       'map': 'ROE_WEIGHT'},
                                        'jroa': {'type': FLOAT, 'en': 'Return on Assets (ROA)', 'size': 70, 'map': 'JROA'},
                                        'roic': {'type': FLOAT, 'en': 'Return on Invested Capital (ROIC)', 'size': 70, 'map': 'ROIC'},
                                        'zxgxl': {'type': FLOAT, 'en': 'Latest Dividend Yield', 'size': 70, 'map': 'ZXGXL'},
                                        'sale_gpr': {'type': FLOAT, 'en': 'Gross Profit Margin', 'size': 70, 'map': 'SALE_GPR'},
                                        'sale_npr': {'type': FLOAT, 'en': 'Net Profit Margin', 'size': 70, 'map': 'SALE_NPR'},
                                        'netprofit_yoy_ratio': {'type': FLOAT, 'en': 'Net Profit Year-over-Year Growth Rate',
                                                                'size': 70, 'map': 'NETPROFIT_YOY_RATIO'},
                                        'deduct_netprofit_growthrate': {'type': FLOAT, 'en': 'Growth Rate of Net Profit Excluding Extraordinary Items',
                                                                        'size': 70, 'map': 'DEDUCT_NETPROFIT_GROWTHRATE'},
                                        'toi_yoy_ratio': {'type': FLOAT, 'en': 'Revenue Year-over-Year Growth Rate', 'size': 70,
                                                          'map': 'TOI_YOY_RATIO'},
                                        'netprofit_growthrate_3y': {'type': FLOAT, 'en': 'Net Profit 3-Year CAGR', 'size': 70,
                                                                    'map': 'NETPROFIT_GROWTHRATE_3Y'},
                                        'income_growthrate_3y': {'type': FLOAT, 'en': 'Revenue 3-Year CAGR', 'size': 70,
                                                                 'map': 'INCOME_GROWTHRATE_3Y'},
                                        'predict_netprofit_ratio': {'type': FLOAT, 'en': 'Predicted Net Profit YoY Growth', 'size': 70,
                                                                    'map': 'PREDICT_NETPROFIT_RATIO'},
                                        'predict_income_ratio': {'type': FLOAT, 'en': 'Predicted Revenue YoY Growth', 'size': 70,
                                                                 'map': 'PREDICT_INCOME_RATIO'},
                                        'basiceps_yoy_ratio': {'type': FLOAT, 'en': 'EPS YoY Growth Rate', 'size': 70,
                                                               'map': 'BASICEPS_YOY_RATIO'},
                                        'total_profit_growthrate': {'type': FLOAT, 'en': 'Total Profit YoY Growth Rate', 'size': 70,
                                                                    'map': 'TOTAL_PROFIT_GROWTHRATE'},
                                        'operate_profit_growthrate': {'type': FLOAT, 'en': 'Operating Profit YoY Growth Rate', 'size': 70,
                                                                      'map': 'OPERATE_PROFIT_GROWTHRATE'},
                                        'debt_asset_ratio': {'type': FLOAT, 'en': 'Debt-to-Asset Ratio', 'size': 70,
                                                             'map': 'DEBT_ASSET_RATIO'},
                                        'equity_ratio': {'type': FLOAT, 'en': 'Equity Ratio', 'size': 70,
                                                         'map': 'EQUITY_RATIO'},
                                        'equity_multiplier': {'type': FLOAT, 'en': 'Equity Multiplier', 'size': 70,
                                                              'map': 'EQUITY_MULTIPLIER'},
                                        'current_ratio': {'type': FLOAT, 'en': 'Current Ratio', 'size': 70,
                                                          'map': 'CURRENT_RATIO'},
                                        'speed_ratio': {'type': FLOAT, 'en': 'Quick Ratio', 'size': 70,
                                                        'map': 'SPEED_RATIO'},
                                        'total_shares': {'type': BIGINT, 'en': 'Total Shares', 'size': 120,
                                                         'map': 'TOTAL_SHARES'},
                                        'free_shares': {'type': BIGINT, 'en': 'Circulating Shares', 'size': 120,
                                                        'map': 'FREE_SHARES'},
                                        'holder_newest': {'type': BIGINT, 'en': 'Latest Number of Shareholders', 'size': 80,
                                                          'map': 'HOLDER_NEWEST'},
                                        'holder_ratio': {'type': FLOAT, 'en': 'Shareholder Growth Rate', 'size': 70,
                                                         'map': 'HOLDER_RATIO'},
                                        'hold_amount': {'type': FLOAT, 'en': 'Average Holding Amount Per Shareholder', 'size': 80,
                                                        'map': 'HOLD_AMOUNT'},
                                        'avg_hold_num': {'type': FLOAT, 'en': 'Average Holding Quantity Per Shareholder', 'size': 70,
                                                         'map': 'AVG_HOLD_NUM'},
                                        'holdnum_growthrate_3q': {'type': FLOAT, 'en': 'Quarterly Growth Rate of Average Holding Quantity', 
                                                                  'size': 70, 'map': 'HOLDNUM_GROWTHRATE_3Q'},
                                        'holdnum_growthrate_hy': {'type': FLOAT, 'en': 'Half-Year Growth Rate of Average Holding Quantity', 
                                                                  'size': 70, 'map': 'HOLDNUM_GROWTHRATE_HY'},
                                        'hold_ratio_count': {'type': FLOAT, 'en': 'Total Shareholding Ratio of Top 10 Shareholders', 
                                                             'size': 70, 'map': 'HOLD_RATIO_COUNT'},
                                        'free_hold_ratio': {'type': FLOAT, 'en': 'Total Circulating Shareholding Ratio of Top 10 Shareholders', 
                                                            'size': 70, 'map': 'FREE_HOLD_RATIO'},
                                        'macd_golden_fork': {'type': BIT, 'en': 'MACD Golden Cross (Daily)', 'size': 70, 
                                                             'map': 'MACD_GOLDEN_FORK'},
                                        'macd_golden_forkz': {'type': BIT, 'en': 'MACD Golden Cross (Weekly)', 'size': 70, 
                                                              'map': 'MACD_GOLDEN_FORKZ'},
                                        'macd_golden_forky': {'type': BIT, 'en': 'MACD Golden Cross (Monthly)', 'size': 70, 
                                                              'map': 'MACD_GOLDEN_FORKY'},
                                        'kdj_golden_fork': {'type': BIT, 'en': 'KDJ Golden Cross (Daily)', 'size': 70, 
                                                            'map': 'KDJ_GOLDEN_FORK'},
                                        'kdj_golden_forkz': {'type': BIT, 'en': 'KDJ Golden Cross (Weekly)', 'size': 70, 
                                                             'map': 'KDJ_GOLDEN_FORKZ'},
                                        'kdj_golden_forky': {'type': BIT, 'en': 'KDJ Golden Cross (Monthly)', 'size': 70, 
                                                             'map': 'KDJ_GOLDEN_FORKY'},
                                        'break_through': {'type': BIT, 'en': 'Breakthrough with High Volume', 'size': 70, 
                                                          'map': 'BREAK_THROUGH'},
                                        'low_funds_inflow': {'type': BIT, 'en': 'Low-Level Net Capital Inflow', 'size': 70, 
                                                             'map': 'LOW_FUNDS_INFLOW'},
                                        'high_funds_outflow': {'type': BIT, 'en': 'High-Level Net Capital Outflow', 'size': 70, 
                                                               'map': 'HIGH_FUNDS_OUTFLOW'},
                                        'breakup_ma_5days': {'type': BIT, 'en': 'Break Above 5-Day Moving Average', 'size': 70, 
                                                             'map': 'BREAKUP_MA_5DAYS'},
                                        'breakup_ma_10days': {'type': BIT, 'en': 'Break Above 10-Day Moving Average', 'size': 70, 
                                                              'map': 'BREAKUP_MA_10DAYS'},
                                        'breakup_ma_20days': {'type': BIT, 'en': 'Break Above 20-Day Moving Average', 'size': 70, 
                                                              'map': 'BREAKUP_MA_20DAYS'},
                                        'breakup_ma_30days': {'type': BIT, 'en': 'Break Above 30-Day Moving Average', 'size': 70, 
                                                              'map': 'BREAKUP_MA_30DAYS'},
                                        'breakup_ma_60days': {'type': BIT, 'en': 'Break Above 60-Day Moving Average', 'size': 70, 
                                                              'map': 'BREAKUP_MA_60DAYS'},
                                        'long_avg_array': {'type': BIT, 'en': 'Long Moving Average Arrangement', 'size': 70, 
                                                           'map': 'LONG_AVG_ARRAY'},
                                        'short_avg_array': {'type': BIT, 'en': 'Short Moving Average Arrangement', 'size': 70, 
                                                            'map': 'SHORT_AVG_ARRAY'},
                                        'upper_large_volume': {'type': BIT, 'en': 'Continuous Rising with High Volume', 'size': 70, 
                                                               'map': 'UPPER_LARGE_VOLUME'},
                                        'down_narrow_volume': {'type': BIT, 'en': 'Decline with Low Volume', 'size': 70, 
                                                               'map': 'DOWN_NARROW_VOLUME'},
                                        'one_dayang_line': {'type': BIT, 'en': 'One Large Bullish Candle', 'size': 70, 
                                                            'map': 'ONE_DAYANG_LINE'},
                                        'two_dayang_lines': {'type': BIT, 'en': 'Two Consecutive Large Bullish Candles', 'size': 70, 
                                                             'map': 'TWO_DAYANG_LINES'},
                                        'rise_sun': {'type': BIT, 'en': 'Rising Sun', 'size': 70, 'map': 'RISE_SUN'},
                                        'power_fulgun': {'type': BIT, 'en': 'Strong Bullish Pattern', 'size': 70, 
                                                         'map': 'POWER_FULGUN'},
                                        'restore_justice': {'type': BIT, 'en': 'Cloud Disperses to See Sun', 'size': 70, 
                                                            'map': 'RESTORE_JUSTICE'},
                                        'down_7days': {'type': BIT, 'en': 'Seven Consecutive Bearish Days', 'size': 70, 
                                                       'map': 'DOWN_7DAYS'},
                                        'upper_8days': {'type': BIT, 'en': 'Eight Consecutive Bullish Days', 'size': 70, 
                                                        'map': 'UPPER_8DAYS'},
                                        'upper_9days': {'type': BIT, 'en': 'Nine Consecutive Bullish Days', 'size': 70, 
                                                        'map': 'UPPER_9DAYS'},
                                        'upper_4days': {'type': BIT, 'en': 'Four Consecutive Bullish Candles', 'size': 70, 
                                                        'map': 'UPPER_4DAYS'},
                                        'heaven_rule': {'type': BIT, 'en': 'Heavenly Rule', 'size': 70, 
                                                        'map': 'HEAVEN_RULE'},
                                        'upside_volume': {'type': BIT, 'en': 'High Volume Uptrend', 'size': 70, 
                                                          'map': 'UPSIDE_VOLUME'},
                                        'bearish_engulfing': {'type': BIT, 'en': 'Bearish Engulfing', 'size': 70, 
                                                              'map': 'BEARISH_ENGULFING'},
                                        'reversing_hammer': {'type': BIT, 'en': 'Inverted Hammer', 'size': 70, 
                                                             'map': 'REVERSING_HAMMER'},
                                        'shooting_star': {'type': BIT, 'en': 'Shooting Star', 'size': 70, 
                                                          'map': 'SHOOTING_STAR'},
                                        'evening_star': {'type': BIT, 'en': 'Evening Star', 'size': 70, 
                                                         'map': 'EVENING_STAR'},
                                        'first_dawn': {'type': BIT, 'en': 'First Light of Dawn', 'size': 70, 
                                                       'map': 'FIRST_DAWN'},
                                        'pregnant': {'type': BIT, 'en': 'Harami (Inside Bar)', 'size': 70, 
                                                     'map': 'PREGNANT'},
                                        'black_cloud_tops': {'type': BIT, 'en': 'Dark Cloud Cover', 'size': 70, 
                                                             'map': 'BLACK_CLOUD_TOPS'},
                                        'morning_star': {'type': BIT, 'en': 'Morning Star', 'size': 70, 
                                                         'map': 'MORNING_STAR'},
                                        'narrow_finish': {'type': BIT, 'en': 'Consolidation with Narrow Range', 'size': 70, 
                                                          'map': 'NARROW_FINISH'},
                                        'limited_lift_f6m': {'type': BIT, 'en': 'Restricted Stock Release in Next 6 Months', 
                                                             'size': 70, 'map': 'LIMITED_LIFT_F6M'},
                                        'limited_lift_f1y': {'type': BIT, 'en': 'Restricted Stock Release in Next Year', 
                                                             'size': 70, 'map': 'LIMITED_LIFT_F1Y'},
                                        'limited_lift_6m': {'type': BIT, 'en': 'Restricted Stock Release in Last 6 Months', 
                                                            'size': 70, 'map': 'LIMITED_LIFT_6M'},
                                        'limited_lift_1y': {'type': BIT, 'en': 'Restricted Stock Release in Last Year', 
                                                            'size': 70, 'map': 'LIMITED_LIFT_1Y'},
                                        'directional_seo_1m': {'type': BIT, 'en': 'Private Placement in Last Month', 
                                                               'size': 70, 'map': 'DIRECTIONAL_SEO_1M'},
                                        'directional_seo_3m': {'type': BIT, 'en': 'Private Placement in Last 3 Months', 
                                                               'size': 70, 'map': 'DIRECTIONAL_SEO_3M'},
                                        'directional_seo_6m': {'type': BIT, 'en': 'Private Placement in Last 6 Months', 
                                                               'size': 70, 'map': 'DIRECTIONAL_SEO_6M'},
                                        'directional_seo_1y': {'type': BIT, 'en': 'Private Placement in Last Year', 
                                                               'size': 70, 'map': 'DIRECTIONAL_SEO_1Y'},
                                        'recapitalize_1m': {'type': BIT, 'en': 'Asset Restructuring in Last Month', 
                                                            'size': 70, 'map': 'RECAPITALIZE_1M'},
                                        'recapitalize_3m': {'type': BIT, 'en': 'Asset Restructuring in Last 3 Months', 
                                                            'size': 70, 'map': 'RECAPITALIZE_3M'},
                                        'recapitalize_6m': {'type': BIT, 'en': 'Asset Restructuring in Last 6 Months', 
                                                            'size': 70, 'map': 'RECAPITALIZE_6M'},
                                        'recapitalize_1y': {'type': BIT, 'en': 'Asset Restructuring in Last Year', 
                                                            'size': 70, 'map': 'RECAPITALIZE_1Y'},
                                        'equity_pledge_1m': {'type': BIT, 'en': 'Equity Pledge in Last Month', 'size': 70, 
                                                             'map': 'EQUITY_PLEDGE_1M'},
                                        'equity_pledge_3m': {'type': BIT, 'en': 'Equity Pledge in Last 3 Months', 'size': 70, 
                                                             'map': 'EQUITY_PLEDGE_3M'},
                                        'equity_pledge_6m': {'type': BIT, 'en': 'Equity Pledge in Last 6 Months', 'size': 70, 
                                                             'map': 'EQUITY_PLEDGE_6M'},
                                        'equity_pledge_1y': {'type': BIT, 'en': 'Equity Pledge in Last Year', 'size': 70, 
                                                             'map': 'EQUITY_PLEDGE_1Y'},
                                        'pledge_ratio': {'type': FLOAT, 'en': 'Equity Pledge Ratio', 'size': 70, 
                                                         'map': 'PLEDGE_RATIO'},
                                        'goodwill_scale': {'type': BIGINT, 'en': 'Goodwill Scale', 'size': 110, 
                                                           'map': 'GOODWILL_SCALE'},
                                        'goodwill_assets_ratro': {'type': FLOAT, 'en': 'Goodwill-to-Net Assets Ratio', 'size': 70, 
                                                                  'map': 'GOODWILL_ASSETS_RATRO'},
                                        'predict_type': {'type': NVARCHAR(length=10), 'en': 'Earnings Forecast Type', 'size': 70, 
                                                         'map': 'PREDICT_TYPE'},
                                        'par_dividend_pretax': {'type': FLOAT, 'en': 'Dividend per Share (Pre-Tax)', 'size': 70, 
                                                                'map': 'PAR_DIVIDEND_PRETAX'},
                                        'par_dividend': {'type': FLOAT, 'en': 'Bonus Share per Share', 'size': 70, 
                                                         'map': 'PAR_DIVIDEND'},
                                        'par_it_equity': {'type': FLOAT, 'en': 'Per Share Capital Increase from Reserve', 'size': 70, 
                                                          'map': 'PAR_IT_EQUITY'},
                                        'holder_change_3m': {'type': FLOAT, 'en': 'Shareholder Change in Last 3 Months', 'size': 70, 
                                                             'map': 'HOLDER_CHANGE_3M'},
                                        'executive_change_3m': {'type': FLOAT, 'en': 'Executive Change in Last 3 Months', 'size': 70, 
                                                                'map': 'EXECUTIVE_CHANGE_3M'},
                                        'org_survey_3m': {'type': SmallInteger, 'en': 'Institutional Surveys in Last 3 Months', 'size': 70, 
                                                          'map': 'ORG_SURVEY_3M'},
                                        'org_rating': {'type': NVARCHAR(length=10), 'en': 'Institutional Rating', 'size': 70, 
                                                       'map': 'ORG_RATING'},
                                        'allcorp_num': {'type': SmallInteger, 'en': 'Total Institutions Holding Shares', 'size': 70, 
                                                        'map': 'ALLCORP_NUM'},
                                        'allcorp_fund_num': {'type': SmallInteger, 'en': 'Number of Funds Holding Shares', 'size': 70, 
                                                             'map': 'ALLCORP_FUND_NUM'},
                                        'allcorp_qs_num': {'type': SmallInteger, 'en': 'Number of Brokerages Holding Shares', 'size': 70, 
                                                           'map': 'ALLCORP_QS_NUM'},
                                        'allcorp_qfii_num': {'type': SmallInteger, 'en': 'Number of QFII Institutions Holding Shares', 'size': 70, 
                                                             'map': 'ALLCORP_QFII_NUM'},
                                        'allcorp_bx_num': {'type': SmallInteger, 'en': 'Number of Insurance Companies Holding Shares', 'size': 70, 
                                                           'map': 'ALLCORP_BX_NUM'},
                                        'allcorp_sb_num': {'type': SmallInteger, 'en': 'Number of Social Security Funds Holding Shares', 'size': 70, 
                                                           'map': 'ALLCORP_SB_NUM'},
                                        'allcorp_xt_num': {'type': SmallInteger, 'en': 'Number of Trust Companies Holding Shares', 'size': 70, 
                                                           'map': 'ALLCORP_XT_NUM'},
                                        'allcorp_ratio': {'type': FLOAT, 'en': 'Total Shareholding Ratio of Institutions', 'size': 70, 
                                                          'map': 'ALLCORP_RATIO'},
                                        'allcorp_fund_ratio': {'type': FLOAT, 'en': 'Shareholding Ratio of Funds', 'size': 70, 
                                                               'map': 'ALLCORP_FUND_RATIO'},
                                        'allcorp_qs_ratio': {'type': FLOAT, 'en': 'Shareholding Ratio of Brokerages', 'size': 70, 
                                                             'map': 'ALLCORP_QS_RATIO'},
                                        'allcorp_qfii_ratio': {'type': FLOAT, 'en': 'Shareholding Ratio of QFII', 'size': 70, 
                                                               'map': 'ALLCORP_QFII_RATIO'},
                                        'allcorp_bx_ratio': {'type': FLOAT, 'en': 'Shareholding Ratio of Insurance Companies', 'size': 70, 
                                                             'map': 'ALLCORP_BX_RATIO'},
                                        'allcorp_sb_ratio': {'type': FLOAT, 'en': 'Shareholding Ratio of Social Security Funds', 'size': 70, 
                                                             'map': 'ALLCORP_SB_RATIO'},
                                        'allcorp_xt_ratio': {'type': FLOAT, 'en': 'Shareholding Ratio of Trust Companies', 'size': 70, 
                                                             'map': 'ALLCORP_XT_RATIO'},
                                        'popularity_rank': {'type': SmallInteger, 'en': 'Popularity Rank in Stock Forums', 'size': 70, 
                                                            'map': 'POPULARITY_RANK'},
                                        'rank_change': {'type': SmallInteger, 'en': 'Popularity Rank Change', 'size': 70, 
                                                        'map': 'RANK_CHANGE'},
                                        'upp_days': {'type': SmallInteger, 'en': 'Consecutive Popularity Increase Days', 'size': 70, 
                                                     'map': 'UPP_DAYS'},
                                        'down_days': {'type': SmallInteger, 'en': 'Consecutive Popularity Decrease Days', 'size': 70, 
                                                      'map': 'DOWN_DAYS'},
                                        'new_high': {'type': SmallInteger, 'en': 'New High Popularity Rank', 'size': 70, 
                                                     'map': 'NEW_HIGH'},
                                        'new_down': {'type': SmallInteger, 'en': 'New Low Popularity Rank', 'size': 70, 
                                                     'map': 'NEW_DOWN'},
                                        'newfans_ratio': {'type': FLOAT, 'en': 'New Fans Ratio', 'size': 70, 
                                                          'map': 'NEWFANS_RATIO'},
                                        'bigfans_ratio': {'type': FLOAT, 'en': 'Loyal Fans Ratio', 'size': 70, 
                                                          'map': 'BIGFANS_RATIO'},
                                        'concern_rank_7days': {'type': SmallInteger, 'en': '7-Day Attention Rank', 'size': 70, 
                                                               'map': 'CONCERN_RANK_7DAYS'},
                                        'browse_rank': {'type': SmallInteger, 'en': 'Daily Browse Rank', 'size': 70, 
                                                        'map': 'BROWSE_RANK'}
                                    }
                                }


CN_STOCK_CPBD = {
    'name': 'cn_stock_cpbd',
    'en': 'Stock Must-Read',
    'columns': {
        'SECURITY_CODE': {'type': NVARCHAR(6), 'en': 'Code'},
        'SECURITY_NAME_ABBR': {'type': NVARCHAR(20), 'en': 'Name'},
        'PE_DYNAMIC': {'type': FLOAT, 'en': 'Dynamic P/E Ratio'},
        'PE_TTM': {'type': FLOAT, 'en': 'P/E Ratio (TTM)'},
        'PE_STATIC': {'type': FLOAT, 'en': 'Static P/E Ratio'},
        'PB_MRQ_REALTIME': {'type': FLOAT, 'en': 'P/B Ratio'},
        'REPORT_DATE': {'type': DATE, 'en': 'Financial Report Date'},
        'EPSJB': {'type': FLOAT, 'en': 'Earnings per Share'},
        'BPS': {'type': FLOAT, 'en': 'Book Value per Share'},
        'MGJYXJJE': {'type': FLOAT, 'en': 'Operating Cash Flow per Share'},
        'MGZBGJ': {'type': FLOAT, 'en': 'Capital Reserve per Share'},
        'MGWFPLR': {'type': FLOAT, 'en': 'Undistributed Profit per Share'},
        'ROEJQ': {'type': FLOAT, 'en': 'Weighted ROE'},
        'XSMLL': {'type': FLOAT, 'en': 'Gross Profit Margin'},
        'ZCFZL': {'type': FLOAT, 'en': 'Debt-to-Asset Ratio'},
        'TOTAL_OPERATEINCOME': {'type': FLOAT, 'en': 'Total Operating Income'},
        'YYZSRGDHBZC': {'type': FLOAT, 'en': 'Operating Income Rolling QoQ Growth'},
        'TOTALOPERATEREVETZ': {'type': FLOAT, 'en': 'Operating Income YoY Growth'},
        'PARENT_NETPROFIT': {'type': FLOAT, 'en': 'Net Profit Attributable to Parent'},
        'NETPROFITRPHBZC': {'type': FLOAT, 'en': 'Net Profit Rolling QoQ Growth'},
        'PARENTNETPROFITTZ': {'type': FLOAT, 'en': 'Net Profit YoY Growth'},
        'KCFJCXSYJLR': {'type': FLOAT, 'en': 'Non-recurring Net Profit'},
        'KFJLRGDHBZC': {'type': FLOAT, 'en': 'Non-recurring Net Profit Rolling QoQ Growth'},
        'KCFJCXSYJLRTZ': {'type': FLOAT, 'en': 'Non-recurring Net Profit YoY Growth'},
        'TOTAL_SHARE': {'type': FLOAT, 'en': 'Total Shares'},
        'FREE_SHARE': {'type': FLOAT, 'en': 'Free Float Shares'},
        'BOARD_NAME': {'type': NVARCHAR(20), 'en': 'Sector'},
        'END_DATE': {'type': DATE, 'en': 'Shareholder Date'},
        'HOLDER_TOTAL_NUM': {'type': FLOAT, 'en': 'Number of Shareholders'},
        'TOTAL_NUM_RATIO': {'type': FLOAT, 'en': 'Change from Previous Period'},
        'AVG_FREE_SHARES': {'type': FLOAT, 'en': 'Average Free Float Shares per Holder'},
        'AVG_FREESHARES_RATIO': {'type': FLOAT, 'en': 'Change in Average Free Float Shares'},
        'HOLD_FOCUS': {'type': FLOAT, 'en': 'Share Concentration'},
        'AVG_HOLD_AMT': {'type': FLOAT, 'en': 'Average Holding Amount per Shareholder'},
        'HOLD_RATIO_TOTAL': {'type': FLOAT, 'en': 'Top 10 Shareholders Holding Ratio'},
        'FREEHOLD_RATIO_TOTAL': {'type': FLOAT, 'en': 'Top 10 Free Float Shareholders Holding Ratio'},
        'LHBD_DATE': {'type': DATE, 'en': 'Dragon-Tiger List Date'},
        'EXPLANATION': {'type': FLOAT, 'en': 'Dragon-Tiger List Explanation'},
        'TOTAL_BUY': {'type': FLOAT, 'en': 'Total Buy Amount'},
        'TOTAL_BUYRIOTOP': {'type': FLOAT, 'en': 'Buy Ratio'},
        'TOTAL_SELL': {'type': FLOAT, 'en': 'Total Sell Amount'},
        'TOTAL_SELLRIOTOP': {'type': FLOAT, 'en': 'Sell Ratio'},
        'DZJY_DATE': {'type': DATE, 'en': 'Block Trade Date'},
        'DEAL_PRICE': {'type': FLOAT, 'en': 'Transaction Price'},
        'PREMIUM_RATIO': {'type': FLOAT, 'en': 'Premium Ratio'},
        'DEAL_VOLUME': {'type': FLOAT, 'en': 'Transaction Volume'},
        'DEAL_AMT': {'type': FLOAT, 'en': 'Transaction Amount'},
        'BUYER_NAME': {'type': FLOAT, 'en': 'Buyer Institution'},
        'SELLER_NAME': {'type': FLOAT, 'en': 'Seller Institution'},
        'RZRQ_DATE': {'type': DATE, 'en': 'Margin Trading Date'},
        'FIN_BUY_AMT': {'type': FLOAT, 'en': 'Margin Purchase Amount'},
        'FIN_REPAY_AMT': {'type': FLOAT, 'en': 'Margin Repayment Amount'},
        'FIN_BALANCE': {'type': FLOAT, 'en': 'Margin Balance'},
        'LOAN_SELL_VOL': {'type': FLOAT, 'en': 'Short Selling Volume'},
        'LOAN_REPAY_VOL': {'type': FLOAT, 'en': 'Short Selling Repayment Volume'},
        'LOAN_BALANCE': {'type': FLOAT, 'en': 'Short Selling Balance'}
    }
}



def get_field_cn(key, table):
    f = table.get('columns').get(key)
    if f is None:
        return key
    return f.get('cn')


def get_field_cns(cols):
    data = []
    for k in cols:
        if k == 'code':
            data.append({"value": k, "caption": cols[k]['cn'], "width": cols[k]['size'],
                         "headerStyle": {"font": "bold 9pt Calibri", "wordWrap": "true"}, "style": ""})
        elif k == 'change_rate':
            data.append({"value": k, "caption": cols[k]['cn'], "width": cols[k]['size'],
                         "headerStyle": {"font": "bold 9pt Calibri", "wordWrap": "true"}, "conditionalFormats": [
                    {"ruleType": "formulaRule", "formula": "@>0", "style": {"foreColor": "red"}},
                    {"ruleType": "formulaRule", "formula": "@<0", "style": {"foreColor": "green"}}]})
        else:
            data.append({"value": k, "caption": cols[k]['cn'], "width": cols[k]['size'],
                         "headerStyle": {"font": "bold 9pt Calibri", "wordWrap": "true"}})
        # data.append({"value": k, "caption": cols[k]['cn'], "width": cols[k]['size'], "headerStyle": {"font": "bold 9pt Calibri", "wordWrap": "true"}})
        # data.append({"name": k, "displayName": cols[k]['cn'], "size": cols[k]['size']})
    return data


def get_field_types(cols):
    data = {}
    for k in cols:
        data[k] = cols[k]['type']
    return data


def get_field_type_name(col_type):
    if col_type == DATE:
        return "datetime"
    elif col_type == FLOAT or col_type == BIGINT or col_type == SmallInteger or col_type == BIT:
        return "numeric"
    else:
        return "string"
